# Generated by Django 5.1.11 on 2025-07-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_rename_phone_number_profile_phone_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="dark_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="newsletter_opt_in",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="secondary_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(blank=True, max_length=60, unique=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="timezone",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
