# Generated by Django 5.1.11 on 2025-06-18 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="productos",
            field=models.ManyToManyField(
                related_name="facturas", through="crm.ItemFactura", to="crm.producto"
            ),
        ),
        migrations.AlterField(
            model_name="itemfactura",
            name="factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="crm.factura",
            ),
        ),
    ]
