# Generated by Django 5.1.6 on 2025-04-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'permissions': [('basic', 'Basic Perm'), ('pro', 'Pro Perm'), ('advanced', 'Advanced Perm')],
            },
        ),
    ]
