name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DJANGO_DEBUG: 'False'
      DATABASE_URL: ${{ secrets.DATABASE_URL }} #This is the Test Database URL from Neon, Secret storage in Github Action Secrets
      
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup Django Secret Key
        run: |
          mykey=$(openssl rand -base64 32)
          echo "DJANGO_SECRET_KEY=$mykey" >> $GITHUB_ENV

      - name: Show Environment Variables
        run: |
          echo ${{ env.DATABASE_URL }}
          echo $DATABASE_URL

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # CORRECCIÓN: Apuntamos a la ruta correcta del archivo
          python -m pip install -r saas/requirements.txt

      - name: Run Django Tests
       
        working-directory: ./saas/src

        run: |
          python manage.py test --keepdb 