name: Django CI/CD

on:
  push:
    branches:
      - Secuvast-Prod
  pull_request:
    branches:
      - Secuvast-Prod

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11'

      - name: Install Neon CLI
        run: npm install -g neonctl
      
      - name: Delete previous Test Branch
        continue-on-error: true # This is good practice
        run: neonctl branches delete "${{env.NEON_GIT_BRANCH}}" --project-id "${{secrets.NEON_PROJECT_ID}}"
        env:
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          NEON_GIT_BRANCH: 'Secuvast-Test-Delete' # Branch to create/delete

      - name: Create Neon Test Branch
        run: |
          neonctl branches create \
            --name "${{env.NEON_GIT_BRANCH}}" \
            --parent "${{env.NEON_PROD_BRANCH}}" \
            --project-id "${{secrets.NEON_PROJECT_ID}}"
        env:
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          NEON_GIT_BRANCH: 'Secuvast-Test-Delete'
          NEON_PROD_BRANCH: 'Secuvast-Prod' # The name of your main DB branch on Neon

      - name: Get Database URL for Test Branch
        id: get_db_url # Give this step an ID
        run: |
          # CORRECTION: Add the --database-name option
          DB_URL=$(neonctl connection-string \
            --branch "${{env.NEON_GIT_BRANCH}}" \
            --database-name "neondb" \
            --project-id "${{secrets.NEON_PROJECT_ID}}")
          
          # This sets the URL for all subsequent steps
          echo "DATABASE_URL=$DB_URL" >> $GITHUB_ENV
        env:
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          NEON_GIT_BRANCH: 'Secuvast-Test-Delete'

      - name: Setup Django Secret Key
        run: echo "DJANGO_SECRET_KEY=$(openssl rand -base64 32)" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r saas/requirements.txt

      - name: Run Django Tests
        env:
          # These variables are now correctly set by the previous steps
          DATABASE_URL: ${{ env.DATABASE_URL }}
          DJANGO_SECRET_KEY: ${{ env.DJANGO_SECRET_KEY }}
          DJANGO_DEBUG: 'False'
        working-directory: ./saas/src
        run: python manage.py test --keepdb

      - name: Clean Up Test Branch
        # This step runs even if the tests fail, to avoid leaving zombie branches
        if: always()
        continue-on-error: true
        run: neonctl branches delete "${{env.NEON_GIT_BRANCH}}" --project-id "${{secrets.NEON_PROJECT_ID}}"
        env:
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          NEON_GIT_BRANCH: 'Secuvast-Test-Delete'