name: Django CI


on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'    
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run tests
        working-directory: ./saas/src
        run: |
          python manage.py test